plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://memory-machine.github.io
baseurl: /oaio

title: Memory Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Memory-Machine
  verb: Memory
  instructions_file: memory.md
  token: openai
  server: https://localhost:443
  apiUrl: https://api.openai.com/v1/responses

app:
  worker_name: oaioapi.js

lm:
  model: gpt-5.2
  max_output_tokens: 100000
  reasoning_effort: high
  reasoning_summary: detailed
  temperature: 1.0

github_settings:
  owner: memory-machine
  repo: memory_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
